/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package holon.simulation.game.submarine;

import org.junit.Test;
import static org.junit.Assert.*;

public class BoardTest {
    @Test public void testNewBoard() {
        Board b = new Board(2);
        String expected = "";
        expected += "25: 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4\n";
        expected += " 0\n";
        expected += " 1\n";
        String actual = b.toString();
        assertEquals(expected, actual);
    }

    @Test public void test3PlayerBoard() {
        Board b = new Board(3);
        String actual = b.toString();
        String[] lines = actual.split("\n");
        assertEquals(" 0", lines[1]);
        assertEquals(" 1", lines[2]);
        assertEquals(" 2", lines[3]);
    }
}
