/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package holon.simulation.game.submarine;

import org.junit.Test;
import static org.junit.Assert.*;

public class BoardTest {
    @Test public void testNewBoard() {
        Board b = new Board(2);
        String expected = "";
        expected += "25: 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 4 4 4 4 4 4 4 4\n";
        expected += " 0\n";
        expected += " 1\n";
        String actual = b.toString();
        assertEquals(expected, actual);
    }
}
